---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	parse_document(parse_document)
	classify_document(classify_document)
	chunk_and_embed(chunk_and_embed)
	__end__([<p>__end__</p>]):::last
	__start__ --> parse_document;
	classify_document --> chunk_and_embed;
	parse_document --> classify_document;
	chunk_and_embed --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
